version: 2
jobs:
  build:
    docker:
      - image: node:8.9-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn test
